*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [VFP80]
***
SET BELL OFF
SET DELETED ON
SET CENTURY ON
SET DATE TO DMY
SET CONSOLE ON
SET RESOURCE OFF
DO FORM reportes
READ EVENTS
ENDPROC
**
*** 
*** ReFox - retrace your steps ... 
***
